import GridCanvasSystem from "./core";
import {
  compilePixelSprite,
  createPixelPalette,
  flipPixelSpriteX,
  flipPixelSpriteY,
  getPixelSpriteBounds,
  hitTestPixelSprite,
  tintPixelSprite,
} from "./drawing/pixelSprite";
import { GridCanvasRuntime } from "./runtime";

const GridCanvasLegacyRuntimeAliases = {
  angleToPoint: GridCanvasRuntime.angleToPoint,
  appendTrailPoint: GridCanvasRuntime.appendTrailPoint,
  canvasToGrid: GridCanvasRuntime.canvasToGrid,
  circlesIntersect: GridCanvasRuntime.circlesIntersect,
  createAnimationLoop: GridCanvasRuntime.createAnimationLoop,
  createKeyTracker: GridCanvasRuntime.createKeyTracker,
  createParticleBurst: GridCanvasRuntime.createParticleBurst,
  createPointerTracker: GridCanvasRuntime.createPointerTracker,
  createSpriteAnimator: GridCanvasRuntime.createSpriteAnimator,
  createStateMachine: GridCanvasRuntime.createStateMachine,
  distanceBetweenPoints: GridCanvasRuntime.distanceBetweenPoints,
  gridToCanvas: GridCanvasRuntime.gridToCanvas,
  hitTestCircleRectangle: GridCanvasRuntime.hitTestCircleRectangle,
  hitTestPoint: GridCanvasRuntime.hitTestPoint,
  hitTestRectangle: GridCanvasRuntime.hitTestRectangle,
  layoutStack: GridCanvasRuntime.layoutStack,
  MassBody: GridCanvasRuntime.MassBody,
  normalizeKeyIdentifier: GridCanvasRuntime.normalizeKeyIdentifier,
  oscillate01: GridCanvasRuntime.oscillate01,
  snapPointToGrid: GridCanvasRuntime.snapPointToGrid,
  stepParticles: GridCanvasRuntime.stepParticles,
  vectorFromAngle: GridCanvasRuntime.vectorFromAngle,
  wrapPoint: GridCanvasRuntime.wrapPoint,
};

const GridCanvasSystemLibrary = Object.assign(GridCanvasSystem, {
  compilePixelSprite,
  createPixelPalette,
  flipPixelSpriteX,
  flipPixelSpriteY,
  getPixelSpriteBounds,
  hitTestPixelSprite,
  tintPixelSprite,
  ...GridCanvasLegacyRuntimeAliases,
  runtime: GridCanvasRuntime,
});

export default GridCanvasSystemLibrary;
export type {
  CanvasTarget,
  GridCanvasClearOptions,
  GridCanvasSystemOptions,
  GridCanvasSystemResolvedOptions,
} from "./core";
export type {
  GridCanvasAsteroidOptions,
  GridCanvasAsteroidShape,
  GridCanvasBarIndicatorOptions,
  GridCanvasCircleSectorOptions,
  GridCanvasGhostOptions,
  GridCanvasMessageOptions,
  GridCanvasPacmanOptions,
  GridCanvasCompiledPixel,
  GridCanvasCompiledPixelSprite,
  GridCanvasCompiledPixelSpriteDrawOptions,
  GridCanvasPixelPalette,
  GridCanvasPixelSprite,
  GridCanvasPixelSpriteDrawOptions,
  GridCanvasPixelSpriteGeometryOptions,
  GridCanvasPoint,
  GridCanvasPolylineOptions,
  GridCanvasProjectileOptions,
  GridCanvasShapeOptions,
  GridCanvasShipOptions,
  GridCanvasStrokeOptions,
  GridCanvasTextOptions,
  GridCanvasValueLabelOptions,
} from "./drawing";
export type {
  AnimationCompleteEvent,
  CanvasPointerEvent,
  CanvasResizeOptions,
  CanvasRuntime,
  CanvasRuntimeOptions,
  CanvasRuntimeSize,
  GridCanvasAnimationLoop,
  GridCanvasAnimationLoopOptions,
  GridCanvasFixedStepLoop,
  GridCanvasFixedStepLoopOptions,
  GridCanvasKeyTracker,
  GridCanvasKeyTrackerOptions,
  GridCanvasGridCell,
  GridCanvasGridOptions,
  GridCanvasScene,
  GridCanvasSceneManager,
  GridCanvasSceneManagerOptions,
  GridCanvasSpriteAnimator,
  GridCanvasSpriteAnimatorOptions,
  GridCanvasStateMachine,
  GridCanvasStateMachineOptions,
  GridCanvasMassBodyOptions,
  GridCanvasPointerTracker,
  GridCanvasPointerTrackerOptions,
  GridCanvasBounds,
  GridCanvasCircleLike,
  GridCanvasCollisionTarget,
  GridCanvasParticle,
  GridCanvasParticleBurstOptions,
  GridCanvasParticleStepOptions,
  GridCanvasRectangleLike,
  GridCanvasSize,
  GridCanvasStackAlign,
  GridCanvasStackDirection,
  GridCanvasStackLayoutOptions,
  GridCanvasTileDefinition,
  GridCanvasTileMap,
  GridCanvasTileMapDrawOptions,
  GridCanvasTileMapDrawRenderer,
  GridCanvasTileMapOptions,
  GridCanvasTileObjectDefinition,
  GridCanvasTileSet,
  GridCanvasVelocity,
  MotionPreference,
  PixelRatioOption,
  PlayAnimationOptions,
  ReducedMotionBehavior,
  SpriteAnimation,
  SpriteAnimatorEvent,
  SpriteAnimatorEventType,
  StateDefinition,
  StateHistoryEntry,
  StateLifecycleContext,
  StateTransitionEvent,
  StateTransitionOptions,
  Unsubscribe,
} from "./runtime";
export {
  CanvasContextUnavailableError,
  CanvasTargetNotFoundError,
  InvalidStateTransitionError,
  RuntimeDestroyedError,
  UnknownAnimationError,
} from "./runtime";
